# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('favorite', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date(2018, 3, 1))),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Wished_for',
            field=models.ManyToManyField(related_name='wishedFor', to='Belt_apps.Users'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='Belt_apps.Users'),
        ),
    ]
