# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_apps', '0002_auto_20180301_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='favorite',
            new_name='favorites',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='Wished_for',
            field=models.ManyToManyField(related_name='wished_For', to='Belt_apps.Users'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='Belt_apps.Users'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date',
            field=models.DateField(default=datetime.date(2018, 3, 2)),
        ),
    ]
