# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(default=datetime.date(2018, 2, 28)),
        ),
    ]
